# Generated by cucumber-sinatra. (2015-01-20 15:13:08 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/lightbox.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Lightbox

class LightboxWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  LightboxWorld.new
end
